<?php
/**
* Implementation of hook_menu
*/
function gmc_spell_correction_menu() {
  $items = array();
  //Menu for display/add spellings.
  $items['manager/spelling'] = array(
    'title' => 'Spell Correction',
    'description' => 'Spell Correction',
	'page callback' => 'spell_correction',
    'access callback' => TRUE,
  );
  //Menu for Delete spellings.
  $items['manager/delete/spelling'] = array(
    'title' => 'Spell Correction',
    'description' => 'Spell Correction',
	'page callback' => 'delete_spelling',
    'access callback' => TRUE,
  );
  //Menu to import spellings.
  $items['manager/import/spelling'] = array(
    'title' => 'Spell Correction',
    'description' => 'Spell Correction',
	'page callback' => 'import_spelling',
    'access callback' => TRUE,
  );
 return $items;
}

/**
* Callback function spell_correction
* for create spelling correction
* @return $output;
*/
function spell_correction() {
	global $user;
	$output = '';
	//Spelling add form
	$output .= drupal_render(drupal_get_form('spell_correction_form'));
	//Table header	
	$header = array(
		array('data' => t('Spell ID'),'field'=>'spell_id', 'sort'=>'asc'),
		array('data' => t('Wrong'),'field'=>'wrong_spell', 'sort'=>'asc'),
		array('data' => t('Right')),
		array('data' => t('Action')),
	);
	//fetch data from pm_draft table
	$sql_query = db_select('gmc_spelling', 'gs');
	$sql_query->fields('gs');
	$sql_query = $sql_query->extend('TableSort')->extend('PagerDefault')->limit(30);
	$result = $sql_query->orderByHeader($header)->execute();
	foreach($result as $data){
		$rows[] = array(
			$data->spell_id,
			$data->wrong_spell,
			$data->right_spell,
			l('Delete', 'manager/delete/spelling', array('query' => array('spell_id' => $data->spell_id))),
		);
	}
	$output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'spell-correction-table')));
	$output .= theme('pager');
	return $output;
}

/**
* Implements form API
* Callback function spell_correction_form
* to save spelling correction
* @return $form
*/
function spell_correction_form() {
	$form['wrong_spell'] = array(
		'#type' => 'textfield', 
		'#title' => t('Wrong'),
	);
	$form['right_spell'] = array(
		'#type' => 'textfield', 
		'#title' => t('Right'),
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	return $form;
}
/**
 * hook_submit for save spell correction.
 * @return '';
 */
function spell_correction_form_submit(&$form, &$form_state) {
	global $user;
	db_insert('gmc_spelling')
		->fields(array('wrong_spell' => $form_state['input']['wrong_spell'], 'right_spell' => $form_state['input']['right_spell']))
		->execute();
	drupal_set_message("Spelling inserted successfully!", "status");
}

/**
* Callback function delete_spelling
* for delete spelling correction
* @return '';
*/
function delete_spelling() {
	$spell_id = $_GET['spell_id'];
	db_delete('gmc_spelling')
	  ->condition('spell_id', $spell_id)
	  ->execute();
	drupal_set_message("Spelling deleted successfully!", "status");
	drupal_goto('manager/spelling');
}
/**
* Callback function import_spelling
* for Import spelling correction from live site table
* @return '';
*/
function import_spelling() {
	/*$data = db_query("SELECT * FROM admin_oskar.Spelling ORDER BY Spelling.ID ASC LIMIT 0, 972");
	foreach($data as $spell) {
		db_insert('dev_syn_drupal.gmc_spelling')
			->fields(array('wrong_spell' => $spell->Wrong, 'right_spell' => $spell->Right))
			->execute();
	}*/
	return '0, 972';
}
