<?php
// This file must be at gmc_views_hand/includes/views directory.

/**
 * @file
 * Definition of gmc_views_hand_handler_handlername.
 */

/**
 * Description of what my handler does.
 */
class gmc_views_hand_handler_frontitle extends views_handler_field {
  /**
   * Add some required fields needed on render().
   */
  function construct() {

  }

  /**
   * Loads additional fields.
   */
  function query() {

  }

  /**
   * Default options form.
   */
  function option_definition() {

  }

  /**
   * Creates the form item for the options added.
   */
  function options_form(&$form, &$form_state) {

  }

  /**
   * Renders the field handler.
   */
  function render($values) {
  return 'dilip';
  }
}
